Reset libbpf to an earlier version to address libz link error
Env: Ubuntu 20.04.1
Ker: 5.4.0-53-generic

```
gcc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp-root-shim \
 xdp-root-shim.c -l:libbpf.a -lelf
/usr/bin/ld: ../libbpf/src//libbpf.a(libbpf.o): undefined reference to symbol 'gzopen64@@ZLIB_1.2.3.3'
/usr/bin/ld: /lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```